/* Cycling Cities — content layer.
   All narrative text carries three languages: en / zh (Traditional Chinese) / nl (Dutch).
   Bibliographic citations in `s` are deliberately left untranslated.
   Dutch strings are a working translation and still need native review. */

const DECADES = [1890, 1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020];

const ERAS = {
  1890: { en: 'The bicycle boom',           zh: '單車熱潮',     nl: 'De fietsboom' },
  1900: { en: 'Paths and licences',         zh: '路權與規費',   nl: 'Paden en vergunningen' },
  1910: { en: 'Streetcar city',             zh: '電車城市',     nl: 'De tramstad' },
  1920: { en: 'Cars enter the street',      zh: '汽車進場',     nl: 'De auto doet zijn intrede' },
  1930: { en: 'Depression and public works',zh: '蕭條與公共工程', nl: 'Crisis en publieke werken' },
  1940: { en: 'Wartime rationing',          zh: '戰時配給',     nl: 'Distributie in oorlogstijd' },
  1950: { en: 'Motorisation',               zh: '汽車化',       nl: 'Motorisering' },
  1960: { en: 'Freeway era',                zh: '高速公路時代', nl: 'Het snelwegtijdperk' },
  1970: { en: 'Protest and oil crisis',     zh: '抗爭與石油危機', nl: 'Protest en oliecrisis' },
  1980: { en: 'Networks planned',           zh: '網絡規劃',     nl: 'Netwerken op de tekentafel' },
  1990: { en: 'Corridors reclaimed',        zh: '廊道再生',     nl: 'Corridors heroverd' },
  2000: { en: 'Revival',                    zh: '復甦',         nl: 'Herleving' },
  2010: { en: 'Systems and data',           zh: '系統與資料',   nl: 'Systemen en data' },
  2020: { en: 'Reallocation',               zh: '空間再分配',   nl: 'Herverdeling van ruimte' }
};

const FACTORS = [
  { id: 'form',   c: '#C15F3C', n: '01',
    label: { en: 'Urban form',             zh: '城市型態', nl: 'Stedelijke vorm' },
    sub:   { en: 'Landscape, density, distance', zh: '地景、密度與騎乘距離', nl: 'Landschap, dichtheid, afstand' } },
  { id: 'alt',    c: '#5B7B7A', n: '02',
    label: { en: 'Mobility alternatives',  zh: '替代運具', nl: 'Mobiliteitsalternatieven' },
    sub:   { en: 'Walking, transit and the car', zh: '步行、公共運輸與汽車', nl: 'Lopen, ov en de auto' } },
  { id: 'policy', c: '#8A7A4E', n: '03',
    label: { en: 'Traffic policy',         zh: '交通政策', nl: 'Verkeersbeleid' },
    sub:   { en: 'Rules, budgets, street space', zh: '法規、預算與空間分配', nl: 'Regels, budgetten, straatruimte' } },
  { id: 'move',   c: '#7A4B52', n: '04',
    label: { en: 'Social movements',       zh: '社會運動', nl: 'Sociale bewegingen' },
    sub:   { en: 'Advocacy, participation, civic action', zh: '倡議、參與與公民行動', nl: 'Actie, participatie, burgerinitiatief' } },
  { id: 'cult',   c: '#565347', n: '05',
    label: { en: 'Cultural status',        zh: '文化地位', nl: 'Culturele status' },
    sub:   { en: 'Identity, gender, everyday meaning', zh: '身分、性別與日常意義', nl: 'Identiteit, gender, alledaagse betekenis' } }
];

/* Modal split, percent by decade: [bicycle, walking, transit, car].
   Indicative interface data — not a research finding. */
const SPLIT = {
  mpls: { 1890:[14,58,24,4], 1900:[16,52,28,4], 1910:[12,44,38,6], 1920:[9,38,36,17], 1930:[8,34,30,28],
          1940:[12,32,28,28], 1950:[5,24,18,53], 1960:[3,18,10,69], 1970:[2,15,7,76], 1980:[2,13,6,79],
          1990:[3,12,6,79], 2000:[4,12,6,78], 2010:[5,13,7,75], 2020:[6,14,6,74] },
  rdam: { 1890:[10,66,22,2], 1900:[18,56,24,2], 1910:[26,46,25,3], 1920:[34,38,24,4], 1930:[42,30,22,6],
          1940:[48,28,18,6], 1950:[38,26,24,12], 1960:[26,20,26,28], 1970:[18,17,23,42], 1980:[16,16,22,46],
          1990:[19,16,21,44], 2000:[22,17,22,39], 2010:[25,18,22,35], 2020:[28,19,21,32] }
};
const SPLIT_C = ['#C15F3C', '#565347', '#5B7B7A', '#BBB8AE'];

/* The wider Cycling Cities research network. */
const NETWORK_CITIES = [
  { ll: [44.9778, -93.265], primary: true,  name: { en: 'Minneapolis', zh: '明尼亞波利斯', nl: 'Minneapolis' } },
  { ll: [51.9244, 4.4777],  primary: true,  name: { en: 'Rotterdam',   zh: '鹿特丹',       nl: 'Rotterdam' } },
  { ll: [38.7223, -9.1393], primary: false, name: { en: 'Lisbon',      zh: '里斯本',       nl: 'Lissabon' } },
  { ll: [47.4979, 19.0402], primary: false, name: { en: 'Budapest',    zh: '布達佩斯',     nl: 'Boedapest' } },
  { ll: [4.711, -74.0721],  primary: false, name: { en: 'Bogotá',      zh: '波哥大',       nl: 'Bogotá' } },
  { ll: [-26.2041, 28.0473],primary: false, name: { en: 'Johannesburg',zh: '約翰尼斯堡',   nl: 'Johannesburg' } },
  { ll: [51.8985, -8.4756], primary: false, name: { en: 'Cork',        zh: '科克',         nl: 'Cork' } },
  { ll: [48.1351, 11.582],  primary: false, name: { en: 'Munich',      zh: '慕尼黑',       nl: 'München' } },
  { ll: [-1.2921, 36.8219], primary: false, name: { en: 'Nairobi',     zh: '奈洛比',       nl: 'Nairobi' } },
  { ll: [45.4642, 9.19],    primary: false, name: { en: 'Milan',       zh: '米蘭',         nl: 'Milaan' } },
  { ll: [-6.7924, 39.2083], primary: false, name: { en: 'Dar es Salaam', zh: '三蘭港',     nl: 'Dar es Salaam' } },
  { ll: [35.6892, 51.389],  primary: false, name: { en: 'Tehran',      zh: '德黑蘭',       nl: 'Teheran' } }
];

/* Era narratives, keyed to decade ranges. Drives the research-story drawer. */
const STORIES = [
  { from: 1890, to: 1900, factor: 'cult',
    era:   { en: 'The boom and the first claims to the road', zh: '單車熱潮與早期路權', nl: 'De boom en de eerste aanspraken op de weg' },
    title: { en: 'What the boom actually meant', zh: '熱潮真正改變了什麼', nl: 'Wat de boom werkelijk betekende' },
    body:  { en: 'The first cycling boom was at once a technical, commercial and status event. Who could buy a bicycle, and who was allowed to ride it, was never a neutral question.',
             zh: '第一波單車熱潮同時是技術、消費與社會地位的事件。誰買得起車、誰被允許上路，從一開始就不是中性的問題。',
             nl: 'De eerste fietsboom was tegelijk een technische, commerciële en statusgebeurtenis. Wie een fiets kon kopen, en wie ermee de weg op mocht, was nooit een neutrale vraag.' } },
  { from: 1910, to: 1910, factor: 'alt',
    era:   { en: 'Rail transit expands', zh: '軌道運輸擴張', nl: 'Het railvervoer breidt uit' },
    title: { en: 'The city on rails', zh: '軌道上的城市', nl: 'De stad op rails' },
    body:  { en: 'Trams and suburban rail redefined commuting distance. In some cities the bicycle retreated to short local trips; in others it grew alongside the rails.',
             zh: '電車與市郊鐵路重新定義了通勤距離。在某些城市，自行車退為短程工具；在另一些城市，它與軌道一起成長。',
             nl: 'Trams en voorstadsspoor herdefinieerden de woon-werkafstand. In sommige steden viel de fiets terug op korte ritten, in andere groeide zij mee met het spoor.' } },
  { from: 1920, to: 1940, factor: 'form',
    era:   { en: 'The bicycle as everyday transport', zh: '自行車成為城市日常', nl: 'De fiets als alledaags vervoer' },
    title: { en: 'The everyday radius changes', zh: '日常半徑正在改變', nl: 'De alledaagse straal verandert' },
    body:  { en: 'The bicycle enlarged the city that walking could reach. Distances for work, shopping and social life were redefined — and with them, ideas about who the street belonged to.',
             zh: '自行車把步行可及的城市放大了。工作、購物與社交的距離開始被重新定義，也改變了街道使用權的想像。',
             nl: 'De fiets vergrootte de stad die te voet bereikbaar was. Afstanden voor werk, winkelen en sociaal leven werden opnieuw gedefinieerd — en daarmee ook de vraag van wie de straat eigenlijk is.' } },
  { from: 1950, to: 1950, factor: 'alt',
    era:   { en: 'Reconstruction and competing modes', zh: '戰後重建與運具競合', nl: 'Wederopbouw en concurrerende vervoerwijzen' },
    title: { en: 'The post-war city moves again', zh: '戰後城市重新移動', nl: 'De naoorlogse stad komt weer in beweging' },
    body:  { en: 'Bicycles, buses and walking carried dense everyday mobility together. How these modes competed and combined shaped the road decisions of the decades that followed.',
             zh: '自行車、公車與步行共同承擔高密度的日常移動；不同運具之間的競合，形塑了後續數十年的道路選擇。',
             nl: 'Fiets, bus en lopen droegen samen de dichte dagelijkse mobiliteit. Hoe deze vervoerwijzen concurreerden en samenwerkten, bepaalde de wegkeuzes van de decennia daarna.' } },
  { from: 1960, to: 1960, factor: 'policy',
    era:   { en: 'Motorisation and segregation', zh: '汽車化與交通分離', nl: 'Motorisering en scheiding van verkeer' },
    title: { en: 'Speed redrew the street', zh: '速度重畫了街道', nl: 'Snelheid tekende de straat opnieuw' },
    body:  { en: 'Engineering built around car volume and efficiency became the norm. Cycling did not disappear, but it was pushed to the margins of policy, statistics and street space.',
             zh: '以汽車流量與效率為核心的工程規劃成為主流。自行車沒有消失，卻在政策、統計與道路空間中被推向邊緣。',
             nl: 'Verkeerskunde rond autovolume en efficiëntie werd de norm. Fietsen verdween niet, maar werd naar de marge van beleid, statistiek en straatruimte gedrukt.' } },
  { from: 1970, to: 1980, factor: 'move',
    era:   { en: 'Civic action and the street turn', zh: '公民行動與街道轉向', nl: 'Burgeractie en de ommekeer in de straat' },
    title: { en: 'Who has a right to the street?', zh: '誰有權使用街道？', nl: 'Wie heeft recht op de straat?' },
    body:  { en: 'Road safety, children and the quality of everyday life returned street design to public debate. Movements showed that urban mobility was never bound to follow one fixed path.',
             zh: '交通安全、兒童與生活環境把道路問題帶回公共辯論。社會運動證明，城市移動並非只能沿著既定路徑前進。',
             nl: 'Verkeersveiligheid, kinderen en de kwaliteit van het dagelijks leven brachten straatontwerp terug in het publieke debat. Bewegingen lieten zien dat stedelijke mobiliteit nooit één vast pad hoefde te volgen.' } },
  { from: 1990, to: 2000, factor: 'form',
    era:   { en: 'Networks and regional integration', zh: '路網化與區域整合', nl: 'Netwerken en regionale integratie' },
    title: { en: 'From single links to a network', zh: '從單一路段到網絡', nl: 'Van losse schakels naar een netwerk' },
    body:  { en: 'Cycling infrastructure came to be treated as a network problem: continuity, junctions and cross-district reach decide whether a lane is actually useful.',
             zh: '自行車設施逐步被視為網絡問題：連續性、節點接續與跨區可達性，決定一條車道是否真正有用。',
             nl: 'Fietsinfrastructuur werd steeds meer als netwerkvraagstuk behandeld: continuïteit, knooppunten en bereik over wijkgrenzen bepalen of een fietspad echt bruikbaar is.' } },
  { from: 2010, to: 2010, factor: 'cult',
    era:   { en: 'Shared systems and cultural repositioning', zh: '共享服務與文化再定位', nl: 'Deelsystemen en culturele herpositionering' },
    title: { en: 'The bicycle becomes visible again', zh: '自行車再次變得可見', nl: 'De fiets wordt weer zichtbaar' },
    body:  { en: 'Bike share, design and city branding brought cycling back into mainstream view — and raised new questions about who can use it and whom it serves.',
             zh: '公共自行車、設計與城市品牌讓自行車重新進入主流視野，也引發誰能使用、為誰服務的新問題。',
             nl: 'Deelfietsen, ontwerp en citybranding brachten fietsen terug in beeld — en riepen nieuwe vragen op over wie het kan gebruiken en wie ermee gediend is.' } },
  { from: 2020, to: 2020, factor: 'alt',
    era:   { en: 'Multimodal and sustainable transition', zh: '多模態與永續轉型', nl: 'Multimodale en duurzame transitie' },
    title: { en: 'Mobility becomes one system', zh: '移動系統走向整合', nl: 'Mobiliteit wordt één systeem' },
    body:  { en: 'Climate, health and equity mean cycling is no longer a single-mode policy but part of a wider transformation of walking, transit and public space.',
             zh: '氣候、健康與公平讓自行車不再是單一運具政策，而是步行、公共運輸與公共空間轉型的一部分。',
             nl: 'Klimaat, gezondheid en rechtvaardigheid maken van fietsen geen apart vervoersbeleid meer, maar onderdeel van een bredere transformatie van lopen, ov en openbare ruimte.' } }
];

const PM_BASE = 'https://yunching0513.github.io/Netherlands-historical-map/pmtiles/';

const CITIES = {
  mpls: {
    name: { en: 'Minneapolis', zh: '明尼亞波利斯', nl: 'Minneapolis' },
    center: [44.96, -93.272], zoom: 13,
    hist: { kind: 'xyz',
      url: 'https://services.arcgisonline.com/ArcGIS/rest/services/USA_Topo_Maps/MapServer/tile/{z}/{y}/{x}',
      label: { en: 'USGS Topo (Esri) · scanned quadrangles', zh: 'USGS Topo (Esri) · 掃描版地形圖', nl: 'USGS Topo (Esri) · gescande kaartbladen' },
      attr: 'USGS / Esri, USA Topo Maps', minZoom: 8, maxZoom: 15 },
    sites: [
      { d: 1890, f: 'form', ll: [44.974, -93.2757],
        t: { en: 'Nicollet Avenue in the bicycle boom', zh: '單車熱潮中的 Nicollet 大道', nl: 'Nicollet Avenue tijdens de fietsboom' },
        n: { en: 'Downtown retail streets absorb the first mass cycling wave; bicycle dealers cluster along four blocks of Nicollet. The nearest surviving street view dates from just after the boom.',
             zh: '市中心的商業街道吸收了第一波大眾騎乘熱潮，自行車行沿 Nicollet 大道四個街廓聚集。目前留存最接近的街景影像，攝於熱潮剛過之後。',
             nl: 'De winkelstraten in het centrum vangen de eerste massale fietsgolf op; fietshandelaren clusteren langs vier blokken van Nicollet. De dichtstbijzijnde bewaarde straatopname dateert van net na de boom.' },
        s: 'Detroit Publishing Co., Nicollet Avenue, Minneapolis, between 1900 and 1906. Library of Congress, Prints & Photographs Division, LC-DIG-det-4a12295.',
        img: { link: 'https://www.loc.gov/item/2016804576/',
          credit: 'Detroit Publishing Company Collection, Library of Congress',
          rights: 'No known restrictions on publication',
          uri: 'https://rightsstatements.org/vocab/NKC/1.0/', cleared: false,
          warn: { en: 'Photograph dates from 1900–1906, later than this decade slice',
                  zh: '照片攝於 1900–1906 年，晚於本年代切片',
                  nl: 'Foto dateert uit 1900–1906, later dan deze decenniumsnede' } } },
      { d: 1890, f: 'cult', ll: [44.968, -93.286],
        t: { en: 'Minneapolis Cycle Path Association', zh: '明尼亞波利斯自行車道協會', nl: 'Minneapolis Cycle Path Association' },
        n: { en: 'Middle-class riders organise to fund gravel side-paths, framing cycling as civic improvement rather than sport.',
             zh: '中產階級騎士自行集資鋪設碎石側道，把騎車定位為市政建設而非運動。',
             nl: 'Fietsers uit de middenklasse organiseren zich om grindpaden naast de weg te bekostigen en presenteren fietsen als stadsverbetering in plaats van sport.' },
        s: 'Bird, P. — Minneapolis research file MPLS-CULT-07' },
      { d: 1900, f: 'policy', ll: [44.9778, -93.265],
        t: { en: 'The cycle path tax stamp', zh: '自行車道稅票', nl: 'De belastingzegel voor het fietspad' },
        n: { en: 'A rider-funded licence stamp pays for the side-path network: an early user-charge experiment in street finance.',
             zh: '由騎士繳費取得的牌照稅票支付側道網絡的建設：街道財政中相當早期的使用者付費實驗。',
             nl: 'Een door fietsers betaalde vergunningzegel financiert het net van zijpaden: een vroeg experiment met gebruikersheffingen in de straatfinanciering.' },
        s: 'Minneapolis City Council proceedings, 1901, vol. 12' },
      { d: 1910, f: 'alt', ll: [44.9483, -93.298],
        t: { en: 'Streetcar network at maximum extent', zh: '電車路網達到最大範圍', nl: 'Tramnet op zijn grootste omvang' },
        n: { en: 'Twin City Rapid Transit reaches its widest reach; cycling recedes to shorter local trips as the tram becomes the default urban journey.',
             zh: 'Twin City Rapid Transit 的路網達到最大範圍；當電車成為城市移動的預設選項，騎乘退回到較短的在地行程。',
             nl: 'Twin City Rapid Transit bereikt zijn grootste bereik; fietsen wijkt terug naar kortere lokale ritten nu de tram de vanzelfsprekende stadsreis wordt.' },
        s: 'Keystone View Company, Scene in the busy northern metropolis, Nicollet Ave., Minneapolis, 1915. Library of Congress, Prints & Photographs Division, stereo 1s13511.',
        img: { link: 'https://www.loc.gov/item/2018649601/',
          credit: 'Keystone View Company · Library of Congress',
          rights: 'No known restrictions on publication',
          uri: 'https://rightsstatements.org/vocab/NKC/1.0/', cleared: false } },
      { d: 1920, f: 'form', ll: [44.98, -93.273],
        t: { en: 'Kerb parking arrives on Hennepin', zh: 'Hennepin 大道出現路邊停車', nl: 'Parkeren langs de stoeprand komt naar Hennepin' },
        n: { en: 'Street space is re-allocated to stationary cars, narrowing the effective riding width on the main downtown spine.',
             zh: '街道空間被重新分配給靜止的汽車，市中心主軸的有效騎乘寬度因此縮減。',
             nl: 'Straatruimte wordt heringedeeld voor stilstaande auto’s, waardoor de bruikbare rijbreedte op de hoofdas van het centrum versmalt.' },
        s: 'Bird, P. — Minneapolis research file MPLS-FORM-22' },
      { d: 1930, f: 'policy', ll: [44.917, -93.25],
        t: { en: 'WPA paving on Minnehaha Parkway', zh: 'WPA 鋪設 Minnehaha 公園道', nl: 'WPA-verharding van de Minnehaha Parkway' },
        n: { en: 'Federal relief work paves the Grand Rounds; recreational riding is formally separated from commuting.',
             zh: '聯邦救濟工程鋪設了 Grand Rounds 公園道系統，休閒騎乘自此在制度上與通勤分離。',
             nl: 'Federale werkverschaffing verhardt de Grand Rounds; recreatief fietsen wordt formeel gescheiden van woon-werkverkeer.' },
        s: 'National Archives, WPA project files, Minnesota 1935–39' },
      { d: 1930, f: 'move', ll: [44.98, -93.279],
        t: { en: 'The 1934 truckers strike', zh: '1934 年卡車司機罷工', nl: 'De vrachtwagenstaking van 1934' },
        n: { en: 'The market district becomes contested political space; who moves through the street is settled by force, not design.',
             zh: '市場區成為政治角力的空間；誰能通行街道，是由武力而非規劃決定。',
             nl: 'De marktwijk wordt betwiste politieke ruimte; wie zich door de straat beweegt, wordt beslist met geweld en niet met ontwerp.' },
        s: 'Minnesota Historical Society, 1934 strike photograph series' },
      { d: 1940, f: 'alt', ll: [44.953, -93.238],
        t: { en: 'Fuel rationing revives the bicycle', zh: '燃料配給讓自行車短暫復甦', nl: 'Brandstofdistributie doet de fiets herleven' },
        n: { en: 'Wartime restrictions produce a short, sharp return to cycling for work trips to the Hiawatha industrial belt.',
             zh: '戰時管制帶來一段短暫而劇烈的回流：前往 Hiawatha 工業帶的通勤重新以自行車完成。',
             nl: 'Oorlogsbeperkingen leiden tot een korte, scherpe terugkeer naar de fiets voor werkritten naar de industriezone langs Hiawatha.' },
        s: 'Office of Price Administration records, district 9' },
      { d: 1950, f: 'form', ll: [44.955, -93.262],
        t: { en: 'I-35W right-of-way cleared', zh: 'I-35W 路權用地清空', nl: 'Tracé voor I-35W vrijgemaakt' },
        n: { en: 'Freeway construction severs north-south neighbourhood connections for two generations of riders.',
             zh: '高速公路興建切斷了南北向的鄰里連結，影響兩個世代的騎乘者。',
             nl: 'De aanleg van de snelweg doorsnijdt noord-zuidverbindingen tussen wijken voor twee generaties fietsers.' },
        s: 'MnDOT right-of-way plans, 1957' },
      { d: 1960, f: 'cult', ll: [44.927, -93.29],
        t: { en: 'The bicycle becomes a child’s toy', zh: '自行車變成兒童玩具', nl: 'De fiets wordt kinderspeelgoed' },
        n: { en: 'Advertising and school policy recast cycling as juvenile, removing it from adult transport planning entirely.',
             zh: '廣告與學校政策把騎車重新定義為兒童活動，使它完全脫離成人交通規劃的視野。',
             nl: 'Reclame en schoolbeleid herdefiniëren fietsen als iets voor kinderen en halen het volledig weg uit de vervoersplanning voor volwassenen.' },
        s: 'Bird, P. — Minneapolis research file MPLS-CULT-31' },
      { d: 1970, f: 'move', ll: [44.97, -93.24],
        t: { en: 'Twin Cities Bicycle Club campaigns', zh: 'Twin Cities Bicycle Club 的倡議行動', nl: 'Campagnes van de Twin Cities Bicycle Club' },
        n: { en: 'Oil-crisis advocacy near the university puts cycling back on the municipal agenda as serious transport.',
             zh: '石油危機期間，大學周邊的倡議行動讓自行車以「正式運具」的身分重回市政議程。',
             nl: 'Belangenbehartiging tijdens de oliecrisis bij de universiteit zet fietsen weer als serieus vervoermiddel op de gemeentelijke agenda.' },
        s: 'TCBC newsletter run, 1972–1979' },
      { d: 1980, f: 'policy', ll: [44.964, -93.313],
        t: { en: 'Cedar Lake rail-to-trail', zh: 'Cedar Lake 廢鐵道改建步道', nl: 'Cedar Lake: van spoorlijn naar fietspad' },
        n: { en: 'Abandoned freight corridors are converted, creating the first grade-separated commuter route into downtown.',
             zh: '廢棄的貨運廊道被轉作他用，形成第一條進入市中心、與車流立體分離的通勤路線。',
             nl: 'Verlaten goederencorridors worden omgebouwd tot de eerste ongelijkvloerse woon-werkroute naar het centrum.' },
        s: 'City of Minneapolis trail acquisition files, 1988' },
      { d: 1990, f: 'form', ll: [44.9482, -93.2765],
        t: { en: 'Midtown Greenway corridor acquired', zh: '取得 Midtown Greenway 廊道', nl: 'Verwerving van de Midtown Greenway-corridor' },
        n: { en: 'A sunken rail trench becomes the spine of the network: the topography of cycling inherited from freight.',
             zh: '一條下沉式鐵道壕溝成為路網的骨幹：騎乘的地形，繼承自貨運鐵路。',
             nl: 'Een verdiepte spoorbak wordt de ruggengraat van het netwerk: de fietstopografie is geërfd van het goederenvervoer.' },
        s: 'Hennepin County Regional Railroad Authority, 1993' },
      { d: 2010, f: 'alt', ll: [44.9765, -93.276],
        t: { en: 'Nice Ride bike share launch', zh: 'Nice Ride 公共自行車上線', nl: 'Lancering van deelfietssysteem Nice Ride' },
        n: { en: 'Docked bike share extends the network into a measurable system with daily origin-destination flows.',
             zh: '有樁式共享自行車把路網延伸成一套可量測的系統，每日起訖流量都留下紀錄。',
             nl: 'Deelfietsen met vaste stations breiden het netwerk uit tot een meetbaar systeem met dagelijkse herkomst-bestemmingsstromen.' },
        s: 'Nice Ride Minnesota, annual report 2011' },
      { d: 2010, f: 'policy', ll: [44.97, -93.267],
        t: { en: 'Protected bikeway plan adopted', zh: '通過保護型自行車道計畫', nl: 'Plan voor vrijliggende fietspaden aangenomen' },
        n: { en: 'Design standards shift from painted lanes to physical separation on Washington Avenue and beyond.',
             zh: '設計標準從彩繪標線轉向實體分隔，先在 Washington Avenue 實施並向外擴展。',
             nl: 'Ontwerpnormen verschuiven van gemarkeerde stroken naar fysieke scheiding, te beginnen op Washington Avenue.' },
        s: 'Minneapolis Protected Bikeway Update, 2015' },
      { d: 2020, f: 'move', ll: [44.948, -93.247],
        t: { en: 'Open Streets expands citywide', zh: 'Open Streets 擴展至全市', nl: 'Open Streets breidt uit over de hele stad' },
        n: { en: 'Temporary car-free days along Lake Street become a routine tool for testing permanent reallocation.',
             zh: 'Lake Street 沿線的臨時無車日，成為測試永久性空間再分配的常態工具。',
             nl: 'Tijdelijke autovrije dagen langs Lake Street worden een vast instrument om permanente herverdeling te testen.' },
        s: 'Our Streets Minneapolis, event archive' }
    ]
  },

  rdam: {
    name: { en: 'Rotterdam', zh: '鹿特丹', nl: 'Rotterdam' },
    center: [51.9225, 4.479], zoom: 14,
    hist: { kind: 'pmtiles', url: PM_BASE + 'rotterdam-1900.pmtiles',
      label: { en: 'Bonneblad 1900 · Kadaster / Topotijdreis', zh: 'Bonneblad 1900 · Kadaster / Topotijdreis', nl: 'Bonneblad 1900 · Kadaster / Topotijdreis' },
      attr: '&copy; Kadaster, CC BY 4.0', minZoom: 12, maxZoom: 17,
      bounds: [[51.9045, 4.4512], [51.9405, 4.5072]] },
    sites: [
      { d: 1900, f: 'form', ll: [51.9225, 4.479],
        t: { en: 'The Coolvest before the fill', zh: '填平之前的 Coolvest', nl: 'De Coolvest vóór de demping' },
        n: { en: 'The Coolvest is still open water. Filling began in 1913 and finished in 1922, turning the moat into the Coolsingel: the city’s first purpose-built modern traffic street.',
             zh: '此時的 Coolvest 仍是開放水域。填平工程始於 1913 年、完成於 1922 年，把這條水道變成 Coolsingel——全市第一條為現代交通而設計的街道。',
             nl: 'De Coolvest is nog open water. De demping begon in 1913 en werd in 1922 voltooid, waarmee de vest veranderde in de Coolsingel: de eerste moderne verkeersstraat die de stad daarvoor speciaal aanlegde.' },
        s: 'Photochrom print, Detroit Publishing Co. / Photoglob Zürich, c.1900. Library of Congress, Photochrom Prints Collection, LC-DIG-ppmsc-05850.',
        img: { commons: 'Rotterdam-Coolsingel-1900.jpg',
          link: 'https://commons.wikimedia.org/wiki/File:Rotterdam-Coolsingel-1900.jpg',
          credit: 'Library of Congress, Photochrom Prints Collection',
          rights: 'Public Domain Mark 1.0',
          uri: 'https://creativecommons.org/publicdomain/mark/1.0/', cleared: true } },
      { d: 1900, f: 'cult', ll: [51.918, 4.475],
        t: { en: 'Cycling as respectable transport', zh: '騎車作為體面的交通方式', nl: 'Fietsen als respectabel vervoer' },
        n: { en: 'Unlike the American case, the bicycle keeps adult, middle-class legitimacy well past 1900.',
             zh: '與美國的情況不同，自行車在 1900 年之後仍長期保有成人、中產階級的正當性。',
             nl: 'Anders dan in de Verenigde Staten behoudt de fiets ook lang na 1900 haar volwassen, burgerlijke status.' },
        s: 'Oldenziel, R. et al. — Cycling Cities country file NL' },
      { d: 1910, f: 'alt', ll: [51.916, 4.482],
        t: { en: 'Tram network expansion at Blaak', zh: 'Blaak 一帶的電車路網擴張', nl: 'Uitbreiding van het tramnet bij de Blaak' },
        n: { en: 'Electric trams and bicycles grow together rather than substituting for one another.',
             zh: '電車與自行車是一起成長的，而非彼此取代。',
             nl: 'Elektrische trams en fietsen groeien samen op in plaats van elkaar te vervangen.' },
        s: 'RET historical route records, 1911' },
      { d: 1920, f: 'form', ll: [51.9235, 4.4785],
        t: { en: 'The Coolsingel opens as a traffic street', zh: 'Coolsingel 以交通幹道之姿啟用', nl: 'De Coolsingel opent als verkeersstraat' },
        n: { en: 'The filled vest becomes a wide boulevard, setting the template for street space allocation in the centre.',
             zh: '填平後的水道成為寬闊的林蔭大道，也為市中心的街道空間分配立下範式。',
             nl: 'De gedempte vest wordt een brede boulevard en zet de norm voor de verdeling van straatruimte in het centrum.' },
        s: 'Stadsarchief Rotterdam, plan collection [reference to be confirmed]' },
      { d: 1920, f: 'policy', ll: [51.927, 4.47],
        t: { en: 'First separated cycle track', zh: '第一條分隔式自行車道', nl: 'Het eerste vrijliggende fietspad' },
        n: { en: 'Separation enters the city’s engineering norms decades before it spreads to other countries.',
             zh: '「分隔」成為市政工程規範的一部分，比其他國家早了數十年。',
             nl: 'Scheiding wordt decennia eerder dan in andere landen onderdeel van de technische normen van de stad.' },
        s: 'Stadsarchief Rotterdam, public works annual report 1924' },
      { d: 1930, f: 'form', ll: [51.9062, 4.4718],
        t: { en: 'Maastunnel planned with a cycle tube', zh: 'Maastunnel 規劃時即納入自行車專用管道', nl: 'Maastunnel ontworpen met een fietsbuis' },
        n: { en: 'A dedicated bicycle bore is designed into major river infrastructure from the outset.',
             zh: '大型跨河基礎建設從一開始就設計了自行車專用坑道。',
             nl: 'Een aparte fietsbuis wordt vanaf het begin meeontworpen in grote rivierinfrastructuur.' },
        s: 'Gemeentewerken Rotterdam, Maastunnel drawings 1937' },
      { d: 1940, f: 'move', ll: [51.921, 4.483],
        t: { en: 'Bicycle confiscation under occupation', zh: '佔領期間的自行車徵收', nl: 'Fietsvordering tijdens de bezetting' },
        n: { en: 'Requisitioning turns the bicycle into a symbol of resistance and national identity.',
             zh: '徵收行動把自行車變成抵抗與民族認同的象徵。',
             nl: 'De vordering maakt van de fiets een symbool van verzet en nationale identiteit.' },
        s: 'NIOD, occupation photograph collection' },
      { d: 1950, f: 'form', ll: [51.92, 4.477],
        t: { en: 'Basisplan reconstruction', zh: 'Basisplan 戰後重建', nl: 'Wederopbouw volgens het Basisplan' },
        n: { en: 'Post-bombing rebuilding adopts a car-oriented modernist plan on cleared ground.',
             zh: '轟炸後的重建在清空的基地上，採用了以汽車為導向的現代主義計畫。',
             nl: 'De wederopbouw na het bombardement volgt op geruimde grond een autogericht modernistisch plan.' },
        s: 'Stadsarchief Rotterdam, Basisplan 1946' },
      { d: 1960, f: 'policy', ll: [51.935, 4.464],
        t: { en: 'Ring road construction', zh: '環城道路興建', nl: 'Aanleg van de ringweg' },
        n: { en: 'High-capacity roads are threaded through the reconstructed fabric north of the centre.',
             zh: '高容量道路被穿插進市中心以北、剛完成重建的城市紋理中。',
             nl: 'Wegen met hoge capaciteit worden door het herbouwde weefsel ten noorden van het centrum geregen.' },
        s: 'Rijkswaterstaat planning files, 1963' },
      { d: 1970, f: 'move', ll: [51.913, 4.49],
        t: { en: 'Stop de Kindermoord', zh: 'Stop de Kindermoord：停止謀殺兒童', nl: 'Stop de Kindermoord' },
        n: { en: 'Child traffic deaths trigger a national movement that permanently changes street design politics. Activists occupied junctions across the country; the photograph shows the Albert Cuypstraat crossing in Amsterdam, 15 December 1972.',
             zh: '兒童交通死亡事件引發全國性運動，永久改變了街道設計的政治。行動者在全國各地占領路口；照片記錄的是 1972 年 12 月 15 日阿姆斯特丹 Albert Cuypstraat 路口。',
             nl: 'Verkeersdoden onder kinderen brengen een landelijke beweging op gang die de politiek van straatontwerp blijvend verandert. Actievoerders bezetten door het hele land kruispunten; de foto toont het kruispunt bij de Albert Cuypstraat in Amsterdam, 15 december 1972.' },
        s: 'Rob Mieremet / Anefo, 15 December 1972. Nationaal Archief, Fotocollectie Anefo, bestanddeelnr. 926-1050.',
        img: { commons: 'Aktiegroep Stop kindermoord bezet kruispunt bij Albert Cuypstraat te Amsterdam, Bestanddeelnr 926-1050.jpg',
          link: 'https://commons.wikimedia.org/wiki/File:Aktiegroep_Stop_kindermoord_bezet_kruispunt_bij_Albert_Cuypstraat_te_Amsterdam,_Bestanddeelnr_926-1050.jpg',
          credit: 'Rob Mieremet / Anefo · Nationaal Archief',
          rights: 'CC0 1.0',
          uri: 'https://creativecommons.org/publicdomain/zero/1.0/', cleared: true,
          warn: { en: 'Image records Amsterdam, not Rotterdam',
                  zh: '影像記錄的是阿姆斯特丹，而非鹿特丹',
                  nl: 'De foto toont Amsterdam, niet Rotterdam' } } },
      { d: 1980, f: 'policy', ll: [51.925, 4.488],
        t: { en: 'Municipal Fietsplan', zh: '市政自行車計畫 Fietsplan', nl: 'Gemeentelijk Fietsplan' },
        n: { en: 'A city-wide plan converts scattered tracks into a coherent, mapped and signed network.',
             zh: '一份全市計畫把零散的車道整合成有地圖、有標示的完整路網。',
             nl: 'Een stadsbreed plan maakt van losse paden een samenhangend netwerk met kaart en bewegwijzering.' },
        s: 'Gemeente Rotterdam, Fietsplan 1982' },
      { d: 1990, f: 'alt', ll: [51.9246, 4.4696],
        t: { en: 'Metro and bicycle parking integrated', zh: '地鐵與自行車停放整合', nl: 'Metro en fietsparkeren geïntegreerd' },
        n: { en: 'Station-level parking makes the bicycle the first and last leg of much longer journeys.',
             zh: '車站層級的停放設施，讓自行車成為長程旅次的第一哩與最後一哩。',
             nl: 'Stallingen bij de stations maken de fiets tot eerste en laatste schakel van veel langere reizen.' },
        s: 'RET station design standards, 1994' },
      { d: 2000, f: 'cult', ll: [51.9195, 4.486],
        t: { en: 'Cycling in city marketing', zh: '城市行銷中的自行車', nl: 'Fietsen in de citymarketing' },
        n: { en: 'The bicycle is repositioned as an asset of a modern, liveable Rotterdam rather than a relic.',
             zh: '自行車被重新定位為現代宜居鹿特丹的資產，而非過去的殘留。',
             nl: 'De fiets wordt niet langer als relikwie gezien, maar gepositioneerd als troef van een modern, leefbaar Rotterdam.' },
        s: 'Rotterdam Marketing, campaign archive' },
      { d: 2010, f: 'form', ll: [51.927, 4.474],
        t: { en: 'Luchtsingel and the Hofbogen', zh: 'Luchtsingel 與 Hofbogen', nl: 'Luchtsingel en de Hofbogen' },
        n: { en: 'Crowd-funded and re-used structures reconnect districts severed by post-war reconstruction.',
             zh: '群眾募資與再利用的構造物，把戰後重建切斷的街區重新縫合。',
             nl: 'Crowdfunding en hergebruikte constructies verbinden wijken die door de wederopbouw waren doorsneden.' },
        s: 'ZUS architects, project documentation 2012' },
      { d: 2020, f: 'policy', ll: [51.9105, 4.4855],
        t: { en: 'Rotterdam cycling vision', zh: '鹿特丹自行車願景', nl: 'Rotterdamse fietsvisie' },
        n: { en: 'Targets shift from network length to comfort, equity, and school-age access across the river.',
             zh: '目標從路網長度，轉向舒適度、公平性，以及過河通學的可達性。',
             nl: 'Doelen verschuiven van netwerklengte naar comfort, rechtvaardigheid en bereikbaarheid voor scholieren aan de overkant van de rivier.' },
        s: 'Gemeente Rotterdam, Fietskoers 2025' }
    ]
  }
};
